### ISSUE TITLE
Export the Eigen dependency

### ISSUE THREAD

**Issue by peci1** [Skydes/tensorflow_catkin#1]
During my experiments in tensorflow_ros I found out the tensorflow libraries use Eigen. So every package providing the tensorflow library should also find_package eigen and export its include_dirs (and possibly also libraries).

**Comment by sarlinpe** [comment]
That's indeed very likely, although I never had this problem with `tensorlfow_catkin`, possibly because [`catkin_simple`](https://github.com/ethz-asl/programming_guidelines/wiki/Catkin-Simple) already takes care of this.

**Comment by peci1** [comment]
I wouldn't say it's because of catkin_simple - much more likely is that you have Eigen installed in a default system location. But not everybody has that.

**Comment by sarlinpe** [comment]
No that's not the case. Tensorflow builds its own Eigen and the corresponding headers get copied into `devel/include`.

**Comment by peci1** [comment]
Ah, ok, this is something the Bazel build doesn't do, so I got confused.
